### ISSUE TITLE
Provide movie recommendations using ML

### ISSUE THREAD

**Issue by georgw777** [georgw777/CS5052-Spark#4]
Provide movie recommendations, e.g., user x liked movies A,B and C therefore theymight like movies X,Y and Z.

**Comment by georgw777** [comment]
@komodo108 Yes, exactly. The API returns 10 movie recommendations when supplied with a user ID. The implementation is such that the ML model (ALS collaborative filtering) is trained when starting up the backend. It persists all recommendations in a table so they don't have to be recomputed.
The method in `api.js` is `API.getRecommendations(userId)` and the return type is the same as for example the search movies function.

**Comment by komodo108** [comment]
Awesome! Thanks so much!! Ill incorporate this into the the displayed results

**Comment by komodo108** [comment]
Implemented in #14
