### ISSUE TITLE
Cluster users by movie taste

### ISSUE THREAD

**Issue by georgw777** [georgw777/CS5052-Spark#6]
Cluster users by movie taste.
See [this example](https://towardsdatascience.com/insights-from-visualizing-public-data-on-twitch-a73304a1b3eb) for ideas

**Comment by georgw777** [comment]
In the commit above, I implemented an endpoint that supplies data about a graph where the nodes are the users and the edges are weighted by the number of movies a given pair of nodes (i.e. users) both watched. @komodo108 is that the info you need for the force-directed graph?

PS: this endpoint is currently very slow, even on the big dataset. Possible solutions:
- precompute this graph on startup
- let the user of the app supply a list of user IDs, and only use those users to create the graph
What do you think?

**Comment by georgw777** [comment]
This endpoint is currently very slow, even on the small dataset. Possible solutions:
- precompute this graph on startup
- let the user of the app supply a list of user IDs, and only use those users to create the graph

Currently, my favoured solution would be the latter because computing the graph takes a few minutes even on the small dataset and the JSON response is already 11MB in size for the small dataset. So if we return the graph only for a subset of users that might be more efficient and useful for visualisation (so it's not too cluttered) in my opinion. What are your thoughts @komodo108

**Comment by georgw777** [comment]
@komodo108 I now changed it such that you need to specify the users for which you want to build the graph. This is significantly faster (only around 20 seconds to build the graph and serve the request).

**Comment by komodo108** [comment]
Alight! Ill incorporate this into the search then! thanks again
