### ISSUE TITLE
Movie names are not cleaned

### ISSUE THREAD

**Issue by komodo108** [georgw777/CS5052-Spark#8]
Some of the movie names are in a strange format and cannot be searched with our current method.
Example: the following should be able to be searched with the query "`The American President`", but currently cannot.
```
11,"American President, The (1995)",Comedy|Drama|Romance
```

**Comment by georgw777** [comment]
This actually turns out to be more difficult than expected. I suggest to leave the search functionality as is and focus on the more pressing issues
